// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqlwrqmqlelfetdkryid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxbHdycW1xbGVsZmV0ZGtyeWlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MDA5NTUsImV4cCI6MjA1NjA3Njk1NX0.3HZBj-o_hiLa3hBBqy-LgEEhIAgctvhEIsLKdMvd92I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);